### ISSUE TITLE
More versions of riscv-tools/verilator

### ISSUE THREAD

**Issue by abejgonzalez** [ucb-bar/riscv-docker-images#1]
@ucbjrl @jackkoenig This is addressing the issue mentioned in riscv-boom/riscv-boom (https://github.com/riscv-boom/riscv-boom/issues/147) about having docker images with riscv-tools and verilator. This first commit has the most updated riscv-tools and the verilator version mentioned in the chisel3 wiki.

**Comment by abejgonzalez** [comment]
Ill wait to push the DockerFile version until I get feedback from you all.

**Comment by ucbjrl** [comment]
Please take a look at https://docs.docker.com/engine/faq/#why-is-debian_frontendnoninteractive-discouraged-in-dockerfiles and https://serverfault.com/questions/618994/when-building-from-dockerfile-debian-ubuntu-package-install-debconf-noninteract.

Why are you installing docker inside the container? That's a new one on me.

I'd also recommend building version 4.008 of verilator.

**Comment by abejgonzalez** [comment]
This DockerFile was changed based off one from CircleCI and they installed Docker. I forgot to delete it when I ported this file here. The other issues are addressed in the PR #2.
